version: "3.9"

services:
  backend:
    build: .
    container_name: chat-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo:6
    container_name: chat-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chatdb
