# .github/workflows/docker-build.yml
name: Build and Push Docker Images

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v5

      # 2. Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      # 3. Log in to Docker Hub using GitHub vars and secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Create backend .env file
      - name: Create backend .env
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > backend/.env

      # 5. Create frontend .env file
      - name: Create frontend .env
        run: |
          echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}" > frontend/.env

      # 6. Build Docker images (frontend + backend)
      - name: Build Docker images
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/mern-frontend:latest --target frontend .
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/mern-backend:latest --target backend .

      # 7. Push Docker images to Docker Hub
      - name: Push Docker images
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/mern-frontend:latest
          docker push ${{ vars.DOCKERHUB_USERNAME }}/mern-backend:latest

      # 8. Show local Docker images for confirmation
      - name: Show Docker images
        run: docker images
